# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 00:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('manufacturer', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=50)),
                ('weight', models.IntegerField(default=0)),
                ('note', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date')),
                ('quantity', models.IntegerField(default=0)),
                ('shipping_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('purchase_channel', models.CharField(max_length=200)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pm.Inventory')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pm.Invoice')),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('last_modified', models.DateTimeField(verbose_name='last modified')),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pm.Inventory')),
            ],
        ),
    ]
