# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 22:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together=set([('name', 'manufacturer', 'color')]),
        ),
    ]
